//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDone.Analytics.Models.Domian
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StartDone_AnalyticsEntities : DbContext
    {
        public StartDone_AnalyticsEntities()
            : base("name=StartDone_AnalyticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Code> Tbl_Code { get; set; }
        public virtual DbSet<Tbl_CodeGroup> Tbl_CodeGroup { get; set; }
        public virtual DbSet<Tbl_IPAddress> Tbl_IPAddress { get; set; }
        public virtual DbSet<Tbl_PageVisit> Tbl_PageVisit { get; set; }
        public virtual DbSet<Tbl_Role> Tbl_Role { get; set; }
        public virtual DbSet<Tbl_Session> Tbl_Session { get; set; }
        public virtual DbSet<Tbl_Visitor> Tbl_Visitor { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
    }
}
