//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDone.Analytics.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PageVisit
    {
        public int PV_ID { get; set; }
        public int PV_VisitorID { get; set; }
        public int PV_LogID { get; set; }
        public string PV_PageUrl { get; set; }
        public string PV_Referrer { get; set; }
        public string PV_WindowSize { get; set; }
        public Nullable<int> PV_BrowerCodeID { get; set; }
        public string PV_BrowerInfo { get; set; }
        public Nullable<int> PV_PlatformCodeID { get; set; }
        public string PV_UserAgent { get; set; }
        public System.DateTime PV_DateTime { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Code Tbl_Code1 { get; set; }
        public virtual Tbl_Log Tbl_Log { get; set; }
        public virtual Tbl_Visitor Tbl_Visitor { get; set; }
    }
}
