//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDone.Analytics.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Session
    {
        public int Session_ID { get; set; }
        public System.Guid Session_Guid { get; set; }
        public System.DateTime Session_StartDateTime { get; set; }
        public System.DateTime Session_LastDateTime { get; set; }
        public int Session_VisitorID { get; set; }
        public Nullable<int> Session_IPID { get; set; }
    
        public virtual Tbl_IPAddress Tbl_IPAddress { get; set; }
        public virtual Tbl_Visitor Tbl_Visitor { get; set; }
    }
}
