//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDone.Analytics.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IPAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_IPAddress()
        {
            this.Tbl_Visitor = new HashSet<Tbl_Visitor>();
            this.Tbl_Session = new HashSet<Tbl_Session>();
        }
    
        public int IA_ID { get; set; }
        public string IA_IP { get; set; }
        public Nullable<int> IA_ContryID { get; set; }
        public Nullable<int> IA_CityID { get; set; }
        public string IA_ISP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Visitor> Tbl_Visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Session> Tbl_Session { get; set; }
    }
}
