//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDone.Analytics.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Code()
        {
            this.Tbl_Visitor = new HashSet<Tbl_Visitor>();
        }
    
        public int Code_ID { get; set; }
        public string Code_Name { get; set; }
        public string Code_Display { get; set; }
        public int Code_CGID { get; set; }
        public bool Code_IsActive { get; set; }
        public System.DateTime Code_CreateDatetime { get; set; }
    
        public virtual Tbl_CodeGroup Tbl_CodeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Visitor> Tbl_Visitor { get; set; }
    }
}
