//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDone.Analytics.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Log()
        {
            this.Tbl_PageVisit = new HashSet<Tbl_PageVisit>();
        }
    
        public int Log_ID { get; set; }
        public string Log_Raw { get; set; }
        public System.DateTime Log_DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PageVisit> Tbl_PageVisit { get; set; }
    }
}
