//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDone.Analytics.Models.Domian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int User_ID { get; set; }
        public int User_RoleID { get; set; }
        public string User_Mobile { get; set; }
        public string User_Name { get; set; }
        public string User_Family { get; set; }
        public string User_PasswordHash { get; set; }
        public string User_PasswordSalt { get; set; }
        public System.DateTime User_CreateDate { get; set; }
        public System.DateTime User_ModifyDate { get; set; }
        public bool User_IsDelete { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
